package com.example.quanlysinhvien.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KetQuaHocTapAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKetQuaHocTapAllPropertiesEquals(KetQuaHocTap expected, KetQuaHocTap actual) {
        assertKetQuaHocTapAutoGeneratedPropertiesEquals(expected, actual);
        assertKetQuaHocTapAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKetQuaHocTapAllUpdatablePropertiesEquals(KetQuaHocTap expected, KetQuaHocTap actual) {
        assertKetQuaHocTapUpdatableFieldsEquals(expected, actual);
        assertKetQuaHocTapUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKetQuaHocTapAutoGeneratedPropertiesEquals(KetQuaHocTap expected, KetQuaHocTap actual) {
        assertThat(actual)
            .as("Verify KetQuaHocTap auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKetQuaHocTapUpdatableFieldsEquals(KetQuaHocTap expected, KetQuaHocTap actual) {
        assertThat(actual)
            .as("Verify KetQuaHocTap relevant properties")
            .satisfies(a -> assertThat(a.getDiemQuaTrinh()).as("check diemQuaTrinh").isEqualTo(expected.getDiemQuaTrinh()))
            .satisfies(a -> assertThat(a.getDiemThanhPhan()).as("check diemThanhPhan").isEqualTo(expected.getDiemThanhPhan()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKetQuaHocTapUpdatableRelationshipsEquals(KetQuaHocTap expected, KetQuaHocTap actual) {
        assertThat(actual)
            .as("Verify KetQuaHocTap relationships")
            .satisfies(a -> assertThat(a.getSinhVien()).as("check sinhVien").isEqualTo(expected.getSinhVien()))
            .satisfies(a -> assertThat(a.getMonHoc()).as("check monHoc").isEqualTo(expected.getMonHoc()));
    }
}
