package com.example.quanlysinhvien.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MonHocAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonHocAllPropertiesEquals(MonHoc expected, MonHoc actual) {
        assertMonHocAutoGeneratedPropertiesEquals(expected, actual);
        assertMonHocAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonHocAllUpdatablePropertiesEquals(MonHoc expected, MonHoc actual) {
        assertMonHocUpdatableFieldsEquals(expected, actual);
        assertMonHocUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonHocAutoGeneratedPropertiesEquals(MonHoc expected, MonHoc actual) {
        assertThat(actual)
            .as("Verify MonHoc auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonHocUpdatableFieldsEquals(MonHoc expected, MonHoc actual) {
        assertThat(actual)
            .as("Verify MonHoc relevant properties")
            .satisfies(a -> assertThat(a.getTenMon()).as("check tenMon").isEqualTo(expected.getTenMon()))
            .satisfies(a -> assertThat(a.getTyLeDiemQuaTrinh()).as("check tyLeDiemQuaTrinh").isEqualTo(expected.getTyLeDiemQuaTrinh()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonHocUpdatableRelationshipsEquals(MonHoc expected, MonHoc actual) {
        // empty method
    }
}
