package com.example.quanlysinhvien.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SinhVienAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinhVienAllPropertiesEquals(SinhVien expected, SinhVien actual) {
        assertSinhVienAutoGeneratedPropertiesEquals(expected, actual);
        assertSinhVienAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinhVienAllUpdatablePropertiesEquals(SinhVien expected, SinhVien actual) {
        assertSinhVienUpdatableFieldsEquals(expected, actual);
        assertSinhVienUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinhVienAutoGeneratedPropertiesEquals(SinhVien expected, SinhVien actual) {
        assertThat(actual)
            .as("Verify SinhVien auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinhVienUpdatableFieldsEquals(SinhVien expected, SinhVien actual) {
        assertThat(actual)
            .as("Verify SinhVien relevant properties")
            .satisfies(a -> assertThat(a.getTenSv()).as("check tenSv").isEqualTo(expected.getTenSv()))
            .satisfies(a -> assertThat(a.getGioiTinh()).as("check gioiTinh").isEqualTo(expected.getGioiTinh()))
            .satisfies(a -> assertThat(a.getNgaySinh()).as("check ngaySinh").isEqualTo(expected.getNgaySinh()))
            .satisfies(a -> assertThat(a.getLop()).as("check lop").isEqualTo(expected.getLop()))
            .satisfies(a -> assertThat(a.getKhoa()).as("check khoa").isEqualTo(expected.getKhoa()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSinhVienUpdatableRelationshipsEquals(SinhVien expected, SinhVien actual) {
        // empty method
    }
}
